### ISSUE TITLE
Filtering at time of calling

### ISSUE THREAD

**Issue by danielo515** [FeiyouG/commander.nvim#10]
Hello,

I was wondering if it would be possible to call command_center with a filter set from the commands? Like `Telescope command_center mode="normal"` to only show keybindings from normal mode.

Sometimes I want to see my keybindings, but I am only interested in the ones in normal mode, or insert mode, etc.

**Comment by FeiyouG** [comment]
That sounds like a good idea. I will put it on my to-do list. Pull requests are also welcomed!

**Comment by FeiyouG** [comment]
Implemented here: 37a0862024a17b2ed68ebb2a4e7f980d28e534d6

**Comment by danielo515** [comment]
Wow,I'm super impressed how fast you added that!
Thank you !
