### ISSUE TITLE
after update command list order is not preserved

### ISSUE THREAD

**Issue by doongjohn** [FeiyouG/commander.nvim#16]
the order of command list display does not match insertion order
```lua
command_center.add({
  {
    description = 'history',
    cmd = '<cmd>FzfLua command_history<cr>',
  }, {
    description = 'tab new',
    cmd = '<cmd>tabnew<cr>',
  }, {
    description = 'tab close',
    cmd = '<cmd>tabclose<cr>',
  },
}, {
  mode = command_center.mode.ADD_ONLY,
  category = "command",
})
```
![image](https://user-images.githubusercontent.com/40219740/181432031-dfbd7852-44f3-4963-8743-1720437656c8.png)

**Comment by FeiyouG** [comment]
This is expected since the last refactor to enhance performance. Do you have a solid reason for why you want commands to be displayed in the order they are inserted?

**Comment by doongjohn** [comment]
no real reason but it looks better if it's not displayed randomly 😄

**Comment by FeiyouG** [comment]
As soon as you type something, the search results will be ordered by their relevancy to the keyword typed. So I don't see this as an issue. 

I am going to close this issue. Feel free to open another one if you find a strong reason or use case to display the results in the order they've been inserted.
