### ISSUE TITLE
[Bug] Plugin broken after last update

### ISSUE THREAD

**Issue by pidgeon777** [FeiyouG/commander.nvim#17]
The following error is generated at Neovim startup after updating the plugin:

```txt
packer.nvim: Error running config for command-center.nvim: ...er\start\command-center.nvim/lua/command_center/init.lua:37: attempt to index local 'opts' (a number value)
```

Packer Config:

```lua
{
  "gfeiyou/command-center.nvim",
    config = function()
      require("user.cc").config()
      end,
    requires = "nvim-telescope/telescope.nvim",
},
```

**Comment by danielo515** [comment]
Facing the same exact problem.

```
packer.nvim: Error running config for command-center.nvim: ...cker/opt/command-center.nvim/lua/command_center/init.lua:37: attempt to index local 'opts' (a number value)
```

**Comment by FeiyouG** [comment]
I just pushed a new commit e61162cfe5efa8333cf2314af08655af5ba98436. Please let me know whether this fixes the problem.

**Comment by danielo515** [comment]
Hello @FeiyouG , that fixes the original problem.
However, now the floating window appears too small:
![image](https://user-images.githubusercontent.com/2270425/181652573-a04fff17-84c5-4171-b07e-23b099707232.png)

Other telescope prompts do not have this problem:

![image](https://user-images.githubusercontent.com/2270425/181652637-3197bda7-4d43-4928-a933-f69914cad88d.png)

**Comment by FeiyouG** [comment]
I don't have this problem at my end. Can you share a minimal config that can reproduce this bug?

**Comment by pidgeon777** [comment]
@FeiyouG Fixed! 🚀

@danielo515 I don't have your floating window issue.

**Comment by danielo515** [comment]
Here you have it @FeiyouG 
https://github.com/danielo515/Telescope-command-center-issue
You may need to clone it with git submodules or just remove the deeply nested packer folder and clone packer into it

**Comment by FeiyouG** [comment]
@danielo515 From what you've shared with me, I don't see you added any commands into command_center. The floating window is too narrow because there was nothing to be displayed.

**Comment by XobSod** [comment]
I have the same issue as @danielo515 has.
I have copied all your example from `command_center.add` and even removed `, command_center.mode.REGISTER_ONLY` from:
```lua

command_center.add({
  {
    desc = "Open command_center",
    cmd = "<CMD>Telescope command_center<CR>",
    keys = {
      {"n", "<Leader>fc", noremap},
      {"v", "<Leader>fc", noremap}
    },
  }
})
```
And I also have narrow palette:
![image](https://user-images.githubusercontent.com/3855655/181830651-9ea6b125-09a6-4c5a-9e01-045156494d7e.png)
And the commands are definitively there because I can scroll through them ;)
![image](https://user-images.githubusercontent.com/3855655/181832109-9eb65714-10c6-49bb-b101-acbe439504b6.png)

**Comment by FeiyouG** [comment]
I found the root cause and fixed it in 125b92306cf29e20d405a5bfe1300af13339e80e. Thank you for bringing this to my attention, @XobSod  and @danielo515.

**Comment by danielo515** [comment]
Thank you for all the effort and quickfixes put into this!!!!
I'll try it tomorrow. Many thanks!

**Comment by danielo515** [comment]
Ok, I couldn't wait and just updated. The problem is totally fixed for me. Many thanks!
