### ISSUE TITLE
After update cannot set keybinding mode to terminal

### ISSUE THREAD

**Issue by theKlisha** [FeiyouG/commander.nvim#20]
Hi, my config is partially broken after update to 31468fd7977f4b79cd2e46f28b7ca36e76fcd940.

Message I'm getting:
```
Invalid declaration of keys:
mode: expected one of { "n", "i", "c", "x", "v" }, got t
{ "t", "<C-\\>", {
    noremap = true
} }
```

Part of config in question:
```
command_center.add({{
    desc = "Toggle terminal",
    cmd = "<CMD>ToggleTerm<CR>",
    keys = {{"n", "<C-\\>", noremap}, {"t", "<C-\\>", noremap}}
}})
```

I have already tried to add `t` to the list in following line, and it seams to solve te issue. Is there any reason why it should't be there?
https://github.com/FeiyouG/command_center.nvim/blob/81a2200d90bcb2477d2db7375fe7aa9b8a9007d5/lua/command_center/constants.lua#L33

Anyway thanks for the work on this plugin. Apart for occasional issues, I really do enjoy using it.

**Comment by FeiyouG** [comment]
I added "t" into `keymap_modes` and tried to register a keymap with terminal mode, and it worked. Could you please check whether 3d2c167fd4689b542e92f92566c51162eb362a10 solves this issue?

**Comment by theKlisha** [comment]
Yes, that solves it. Thank you.
