### ISSUE TITLE
I don't think this plugin is needed

### ISSUE THREAD

**Issue by yimingwangdell** [FeiyouG/commander.nvim#35]
we should write keymaps, or using : in vim, if taking a step back, we still have Telescope Commands to search commands, I don't think add another menu is meaningful.

**Comment by younger-1** [comment]
I like the idea of this plugin as it allows me to:

1. search among the keymaps and commands
2. search by description in case forgetting the command name

Just like vscode's command pane, but with customizable description.

**Comment by FeiyouG** [comment]
> we should write keymaps, or using : in vim, if taking a step back, we still have Telescope Commands to search commands, I don't think add another menu is meaningful.

`:` can't fuzzy search, plus if you forget which command to use, you have to look up `:help` or the doc of the plug-in. 

And if you really don't like this plugin, then you don't have to use it. It's just that simple :)
