### ISSUE TITLE
Set telescope width

### ISSUE THREAD

**Issue by mil-ad** [FeiyouG/commander.nvim#39]
Is there a way to set the telescope width when using commander? I have the following in my telescope `setup()` but it doesn't seem to be picked up by commander and instead it's set to minimum required

```
  defaults = {
    layout_config = {
      horizontal = { height = 0.65, width=0.9 }
    },
  }
```

**Comment by FeiyouG** [comment]
Hi @mil-ad, you need to specify which theme to use in Commander's config: https://github.com/FeiyouG/commander.nvim#telescopenvim

You can pass in exact same theme you are using for telescope.

**Comment by mil-ad** [comment]
Thanks @FeiyouG! I tried a couple of combinations but didn't manage to get it to work:

* `theme = require("telescope.themes").get_ivy`
* `theme = require("telescope.themes").get_ivy()`
* `theme = require("telescope.themes").get_ivy({})`
* `theme = require("telescope.themes").ivy`

**Comment by mil-ad** [comment]
@FeiyouG I believe this is broken. I have tried specifying the theme but commander width is still determined by the length of items passed.
